CREATE DATABASE FIFAWC2026;
USE FIFAWC2026;
SHOW TABLES;
-- mysql FIFA WORLD CUP SCHEMA
# THESE QUERIES CREATE THE DATABASE AND THE 5 TABLES WITHIN THE DATABASE

# THE FIRST TABLE IS THE TEAMS TABLE

DROP TABLE IF EXISTS FIFA_TEAMS;
CREATE TABLE FIFA_TEAMS
(
   TEAM_ID INT PRIMARY KEY,
   COUNTRY VARCHAR(60),
   FIFA_CODE CHAR(3),
   FIFA_RANKING INT);

# THE SECOND IS THE PLAYERS TABLE

DROP TABLE IF EXISTS PLAYERS;
CREATE TABLE PLAYERS
(
   PLAYER_ID INT PRIMARY KEY,
   TEAM_ID INT,
   FULL_NAME VARCHAR(100),
   AGE INT);


# THE THIRD IS THE MATCHES TABLE
   
DROP TABLE IF EXISTS MATCHES;
CREATE TABLE MATCHES
(
  MATCH_ID INT PRIMARY KEY,
  MATCH_DATE DATE,
  STAGE VARCHAR (30),
  GROUP_NAME VARCHAR (10));
   
# THE FOURTH IS THE MATCH STAT TABLE

DROP TABLE IF EXISTS MATCH_STAT;
CREATE TABLE MATCH_STAT
(
  STAT_ID INT PRIMARY KEY,
  MATCH_ID INT,
  TEAM_ID INT,
  GOALS_SCORED INT);
  
# THE FIFTH IS THE GOALS TABLE
  
DROP TABLE IF EXISTS GOALS;
CREATE TABLE GOALS
(
  GOAL_ID INT PRIMARY KEY,
  MATCH_ID INT,
  PLAYER_ID INT,
  TIME_SCORED INT);
      
   
   

