USE FIFAWC2026;
SHOW TABLES;
# THE FOLLOWING 3 BASIC QUERIES SELECT EVERYTHING FROM THE GOALS, FIFA_TEAMS AND PLAYERS TABLES AND LETS US KNOW WHAT WE ARE WORKING WITH

SELECT * FROM GOALS;
SELECT * FROM FIFA_TEAMS;
SELECT * FROM PLAYERS;

# THIS 4TH QUERY SHOWS ALL THE GOALS SCORED BY PLAYER 4 AS RECORDED ON THE GOALS TABLE

SELECT * FROM GOALS
WHERE PLAYER_ID = 4;

# THE FOLLOWING QUERY (5TH QUERY) HELPS US SEE THE COUNTRIES IN THE WORLD CUP ORDERED BY FIFA RANKING

SELECT COUNTRY, FIFA_RANKING
FROM FIFA_TEAMS
ORDER BY FIFA_RANKING;

# THIS 6TH QUERY SELECTS ONLY THOSE COUNTRIES AND THEIR RANKING THAT BEGIN WITH THE LETTER C FROM THE FIFA_TEAMS TABLE USING THE LIKE OPERATOR

SELECT COUNTRY, FIFA_RANKING
FROM FIFA_TEAMS
WHERE COUNTRY LIKE 'C%';

# IN THIS 7TH QUERY WE ARE LOOKING FOR PLAYERS WHO SCORED MORE THAN 1 GOAL
SELECT 
    P.FULL_NAME,
    COUNT(g.GOAL_ID) AS TOTAL_GOALS
FROM PLAYERS P
JOIN GOALS G
    ON P.PLAYER_ID = G.PLAYER_ID
GROUP BY P.PLAYER_ID, P.FULL_NAME
HAVING COUNT(G.GOAL_ID) > 1
ORDER BY TOTAL_GOALS DESC;
SELECT * FROM MATCH_STAT;

# THE 8TH STATEMENT LOOKS FOR THE AVERAGE, MINIMUM AND MAXIMUM GOALS SCORED ON THE MATCH_STAT TABLE

SELECT 
    AVG(GOALS_SCORED) AS AverageGoals,
    MIN(GOALS_SCORED) AS LowestGoals,
    MAX(GOALS_SCORED) AS HighestGoals
FROM MATCH_STAT;

# THE FOLLOWING STATEMENT USES A NESTED SUBQUERY TO OBTAIN THE AVERAGE GOALS PER MATCH AS WELL AS THE LOWEST AND HIGHEST GOALS
SELECT
    AVG(TotalGoals) AS AVG_GOALS_PER_MATCH,
    MIN(TotalGoals) AS LOWEST_GOALS,
    MAX(TotalGoals) AS HIGHEST_GOALS
FROM (
    SELECT 
        MATCH_ID,
        SUM(GOALS_SCORED) AS TotalGoals
    FROM MATCH_STAT
    GROUP BY MATCH_ID
) AS MATCH_TOTALS;

# THE FOLLOWING USES A LEFT JOIN TO KEEP ALL PLAYERS FROM THE PLAYERS TABLE EVEN IF THEY HAVE NOT SCORED

SELECT 
    P.PLAYER_ID,
    P.FULL_NAME,
    COUNT(G.GOAL_ID) AS TotalGoals
FROM PLAYERS P
LEFT JOIN GOALS G
    ON P.PLAYER_ID = G.PLAYER_ID
GROUP BY P.PLAYER_ID, P.FULL_NAME
ORDER BY TotalGoals DESC;



# I USED A BIT OF AI BOTH GOOGLE AND CHAT TO BRAINSTORM HOW TO STRUCTURE MY DATABASE AND TO ORGANIZE MY TABLE STRUCTURE 
# SO THAT I COULD ENSURE IT WOULD PROVIDE MY DESIRED RESULTS IN THE DATABASE
# IT WAS NECESSARY TO USE IT ALSO TO COLLECT THE DATA AS I WAS USING A REAL WORLD SCENARIO OF THE FIFA WORLD CUP HELD IN JULY OF THIS YEAR
# AI COULD NOT DECIDE WHAT MY INTEREST WAS OR EXACTLY WHAT I WANTED TO TEST FOR IN MY DATABASE SO I DID THAT
# I MADE SURE TO STRUCTURE MAJORITY OF MY QUERIES FROM WHAT I UNDERSTOOD FROM THE COURSE AND USED AI TO CLARIFY UNDERSTANDING OF JOINS AND NESTED SUBQUERIES
# I FOUND IT ALL EXCITING LIKE A LEARNING ADVENTURE 