# I HAVE CREATED 3 INDEXES FOLLOWING THE STEPS BELOW
USE FIFAWC2026;
SHOW TABLES;
SHOW INDEX FROM FIFA_TEAMS;
SHOW INDEX FROM PLAYERS;
SHOW INDEX FROM MATCHES;
SHOW INDEX FROM GOALS;
SHOW INDEX FROM MATCH_STAT;
DESCRIBE MATCH_STAT;

# THE INDEX ON GOALS HELPS SPEED UP SEARCHES AND JOIN OPERATIONS WHEN FINDING GOALS 
# SCORED BY A SPECIFIC PLAYER AND THE MATCHES IN WHICH THEY SCORED.

CREATE INDEX IDX_GOALS_PLAYER_MATCH
ON GOALS (PLAYER_ID, MATCH_ID);

SHOW INDEX FROM GOALS;


# THE FOLOWING UNIQUE INDEX ON MATCH ID AND TEAM ID IN MATCH_STAT TABLE HELPS SPEED UP JOINS INVOLVING A SPECIFIC MATCH
# AND ITS PARTICIPATING TEAMS. IT ALSO ENSURES THAT THE SAME TEAM WILL NOT BE ENTERED TWICE FOR THE SAME MATCH

CREATE UNIQUE INDEX IDX_MATCH_STAT_MATCH_TEAM
ON MATCH_STAT (MATCH_ID, TEAM_ID);
SHOW INDEX FROM MATCH_STAT;

# THIS INDEX ON FIFA_Ranking IN THE TEAMS TABLES HELPS QUERIES THAT FILTER OR SORT TEAMS ACCORDING TO FIFA RANKING.

CREATE INDEX IDX_FIFA_TEAMS_FIFA_RANKING
ON FIFA_TEAMS (FIFA_RANKING);
SHOW INDEX FROM FIFA_TEAMS;